-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgiOAskuJdLspjnSSE
mGhVQZ0cRM4bxLpn3lKVUNMyQUugCgYIKoZIzj0DAQehRANCAAQgF2xwsN2aM7MD
/5FKt7IQ0IxP+j7pR/GQWxu7L5b8oaOIe0SxzrEJoLeSJdbLKZADjQpu35OMWynR
Eze4/6Vk
-----END PRIVATE KEY-----