import {IWatchDetailContainer} from './IWatch';

export {default as SplashContainer} from './Splash/SplashContainer';
export {default as EmailContainer} from '../screens/Auth/Login/EmailContainer';
export {default as PasswordContainer} from '../screens/Auth/Login/PasswordContainer';
export {default as ForgotPassword} from '../screens/Auth/ForgotPassowrd/ForgotPasswordContainer';
export {default as VerifyCode} from '../screens/Auth/ForgotPassowrd/VerifyCodeContainer';
export {default as ResetPassword} from '../screens/Auth/ForgotPassowrd/ResetPasswordContainer';
export {default as OTPContainer} from '../screens/Auth/SignUp/OTP/OTPContainer';
export {default as SignUpContainer} from '../screens/Auth/SignUp/SignUpContainer';
export {default as ProfileContainer} from '../screens/Profile/ProfileContainer';

export {default as HomeContainer} from './Home/HomeContainer';
export {default as ChatListContainer} from '../screens/Chat/ChatList/ChatListContainer';
export {default as ChatDetail} from '../screens/Chat/ChatDetail/ChatDetailContainer';
export {default as IWatchContainer} from '../screens/IWatch/IWatchContainer';
export {default as ContactUs} from '../screens/ContactUs/ContactUsContainer';
export {default as PrivacyPolicy} from '../screens/PrivacyPolicy/PrivacyPolicyContainer';
export {default as TermsCondition} from '../screens/TermsCondition/TermsConditionContainer';
export {default as FaqsContainer} from '../screens/Faqs/FaqsContainer';
export {default as AboutUs} from '../screens/AboutUs/AboutUsContainer';
export {default as Notification} from '../screens/Notification/NotificationContainer';
export {default as ProductDetailContainer} from '../screens/Home/ProductDetail/ProductDetailContainer';
export {default as RatingReviews} from '../screens/RatingReviews/RatingReviewsContainer';
export {default as Catagories} from '../screens/Catagories/CatagoriesContainer';
export {default as ReportContainer} from '../screens/Report/ReportContainer';
export {default as IBuyContainer} from '../screens/IBuy/IBuyContainer';
export {default as AccountSetting} from '../screens/AccountSetting/AccountSettingContainer';
export {default as ISellContainer} from './ISell/ISellContainer';
export {default as VehicalForSale} from './ISell/VehicalForSale/VehicalForSaleContainer';
export {default as PropertyForSale} from './ISell/PropertyForSale/PropertyForSaleContainer';
export {default as ISellContainerCard} from '../screens/ISellContainer/ISellContainer';
export {default as IWonLostContainer} from '../screens/IWonLost/IWonLostContainer';
export {default as RecievedOffers} from '../screens/RecievedOffers/RecievedOfferContainer';
export {default as RecievedOfferDetail} from '../screens/RecievedOfferDetail/RecievedOfferDetailContainer';
export {default as BuyerOffersContainer} from '../screens/RecievedOffers/BuyerOffersContainer';
